export const STATIC_BUSINESS_TYPES = [
  "Công ty TNHH 1 thành viên",
  "Công ty TNHH 2 thành viên trở lên",
  "Công ty cổ phần",
  "Công ty hợp danh",
  "Doanh nghiệp tư nhân",
  "Hộ kinh doanh",
  "Hợp tác xã",
  "Chi nhánh",
] as const;

export interface IndustryLevel4 {
  code: string;
  name: string;
}

export const STATIC_INDUSTRIES_LEVEL4: IndustryLevel4[] = [
  { code: "0111", name: "Trồng lúa" },
  { code: "0112", name: "Trồng ngô và cây lương thực có hạt khác" },
  { code: "0113", name: "Trồng cây lấy củ có chất bột" },
  { code: "0114", name: "Trồng cây mía" },
  { code: "0115", name: "Trồng cây thuốc lá, thuốc lào" },
  { code: "0116", name: "Trồng cây lấy sợi" },
  { code: "0117", name: "Trồng cây có hạt chứa dầu" },
  { code: "0118", name: "Trồng rau, đậu các loại và trồng hoa" },
  { code: "0121", name: "Trồng cây ăn quả" },
  { code: "0122", name: "Trồng cây lấy quả chứa dầu" },
  { code: "0123", name: "Trồng cây điều" },
  { code: "0124", name: "Trồng cây tiêu" },
  { code: "0125", name: "Trồng cây cao su" },
  { code: "0126", name: "Trồng cây cà phê" },
  { code: "0127", name: "Trồng cây chè" },
  { code: "0128", name: "Trồng cây gia vị, cây dược liệu" },
  { code: "0129", name: "Trồng cây công nghiệp lâu năm khác" },
  { code: "0141", name: "Chăn nuôi trâu, bò" },
  { code: "0142", name: "Chăn nuôi ngựa, lừa, la" },
  { code: "0144", name: "Chăn nuôi dê, cừu" },
  { code: "0145", name: "Chăn nuôi lợn" },
  { code: "0146", name: "Chăn nuôi gia cầm" },
  { code: "0149", name: "Chăn nuôi khác" },
  { code: "0210", name: "Trồng và chăm sóc rừng" },
  { code: "0220", name: "Khai thác gỗ" },
  { code: "0311", name: "Khai thác thủy sản biển" },
  { code: "0312", name: "Khai thác thủy sản nội địa" },
  { code: "0321", name: "Nuôi trồng thủy sản biển" },
  { code: "0322", name: "Nuôi trồng thủy sản nội địa" },
  { code: "1010", name: "Chế biến và bảo quản thịt" },
  { code: "1020", name: "Chế biến và bảo quản thủy sản" },
  { code: "1030", name: "Chế biến và bảo quản rau quả" },
  { code: "1040", name: "Sản xuất dầu, mỡ động, thực vật" },
  { code: "1050", name: "Chế biến sữa và các sản phẩm từ sữa" },
  { code: "1061", name: "Xay xát và sản xuất bột lương thực" },
  { code: "1071", name: "Sản xuất các loại bánh từ bột" },
  { code: "1072", name: "Sản xuất đường" },
  { code: "1073", name: "Sản xuất ca cao, sô cô la và mứt kẹo" },
  { code: "1074", name: "Sản xuất mì ống, mì sợi và các sản phẩm tương tự" },
  { code: "1075", name: "Sản xuất món ăn, thức ăn chế biến sẵn" },
  { code: "1079", name: "Sản xuất thực phẩm khác chưa phân vào đâu" },
  { code: "1080", name: "Sản xuất thức ăn gia súc, gia cầm và thuỷ sản" },
  { code: "1101", name: "Chưng, tinh cất và pha chế các loại rượu mạnh" },
  { code: "1102", name: "Sản xuất rượu vang" },
  { code: "1103", name: "Sản xuất bia và mạch nha chưng cất bia" },
  { code: "1104", name: "Sản xuất đồ uống không cồn, nước khoáng" },
  { code: "1311", name: "Chuẩn bị và kéo sợi dệt" },
  { code: "1312", name: "Dệt vải" },
  { code: "1313", name: "Hoàn thiện sản phẩm dệt" },
  { code: "1410", name: "May trang phục (trừ trang phục bằng da lông thú)" },
  { code: "1520", name: "Sản xuất giày, dép" },
  { code: "1610", name: "Cưa, xẻ, bào gỗ và bảo quản gỗ" },
  { code: "1621", name: "Sản xuất gỗ dán, gỗ lạng, ván ép và ván mỏng khác" },
  { code: "1622", name: "Sản xuất đồ gỗ xây dựng" },
  { code: "1701", name: "Sản xuất bột giấy, giấy và bìa" },
  { code: "1702", name: "Sản xuất giấy nhăn, bìa nhăn, bao bì từ giấy và bìa" },
  { code: "1811", name: "In ấn" },
  { code: "2011", name: "Sản xuất hóa chất cơ bản" },
  { code: "2012", name: "Sản xuất phân bón và hợp chất ni tơ" },
  { code: "2013", name: "Sản xuất chất dẻo và cao su tổng hợp dạng nguyên sinh" },
  { code: "2021", name: "Sản xuất thuốc trừ sâu và hóa chất lâm nghiệp khác" },
  { code: "2022", name: "Sản xuất sơn, vecni và các chất quét tương tự" },
  { code: "2023", name: "Sản xuất mỹ phẩm, xà phòng, chất tẩy rửa" },
  { code: "2100", name: "Sản xuất thuốc, hóa dược và dược liệu" },
  { code: "2220", name: "Sản xuất các sản phẩm từ chất dẻo" },
  { code: "2394", name: "Sản xuất xi măng, vôi và thạch cao" },
  { code: "2410", name: "Sản xuất sắt, thép, gang" },
  { code: "2511", name: "Sản xuất các cấu kiện kim loại" },
  { code: "2610", name: "Sản xuất linh kiện điện tử" },
  { code: "2620", name: "Sản xuất máy vi tính và thiết bị ngoại vi của máy vi tính" },
  { code: "2630", name: "Sản xuất thiết bị truyền thông" },
  { code: "2640", name: "Sản xuất sản phẩm điện tử dân dụng" },
  { code: "2710", name: "Sản xuất mô tơ, máy phát, biến thế điện, thiết bị phân phối" },
  { code: "2720", name: "Sản xuất pin và ắc quy" },
  { code: "2732", name: "Sản xuất dây, cáp điện và điện tử khác" },
  { code: "2740", name: "Sản xuất thiết bị chiếu sáng" },
  { code: "2750", name: "Sản xuất đồ điện gia dụng" },
  { code: "2811", name: "Sản xuất động cơ, tuabin (trừ động cơ máy bay, ô tô)" },
  { code: "2910", name: "Sản xuất ô tô và xe có động cơ khác" },
  { code: "3011", name: "Đóng tàu và cấu kiện nổi" },
  { code: "3100", name: "Sản xuất giường, tủ, bàn, ghế" },
  { code: "3211", name: "Sản xuất đồ kim hoàn và chi tiết liên quan" },
  { code: "3230", name: "Sản xuất dụng cụ thể dục, thể thao" },
  { code: "3240", name: "Sản xuất đồ chơi, trò chơi" },
  { code: "3250", name: "Sản xuất thiết bị, dụng cụ y tế, nha khoa" },
  { code: "4100", name: "Xây dựng nhà các loại" },
  { code: "4210", name: "Xây dựng công trình đường sắt và đường bộ" },
  { code: "4220", name: "Xây dựng công trình công ích (điện, nước, viễn thông)" },
  { code: "4290", name: "Xây dựng công trình kỹ thuật dân dụng khác" },
  { code: "4311", name: "Phá dỡ" },
  { code: "4312", name: "Chuẩn bị mặt bằng" },
  { code: "4321", name: "Lắp đặt hệ thống điện" },
  { code: "4322", name: "Lắp đặt hệ thống cấp, thoát nước, lò sưởi và điều hoà" },
  { code: "4329", name: "Lắp đặt hệ thống xây dựng khác" },
  { code: "4330", name: "Hoàn thiện công trình xây dựng" },
  { code: "4390", name: "Hoạt động xây dựng chuyên dụng khác" },
  { code: "4511", name: "Bán ô tô và xe có động cơ khác" },
  { code: "4512", name: "Đại lý bán ô tô và xe có động cơ khác" },
  { code: "4520", name: "Bảo dưỡng, sửa chữa ô tô và xe có động cơ khác" },
  { code: "4530", name: "Bán phụ tùng và các bộ phận phụ trợ của ô tô" },
  { code: "4541", name: "Bán mô tô, xe máy" },
  { code: "4543", name: "Bảo dưỡng và sửa chữa mô tô, xe máy" },
  { code: "4610", name: "Đại lý, môi giới, đấu giá hàng hóa" },
  { code: "4620", name: "Bán buôn nông, lâm sản nguyên liệu và động vật sống" },
  { code: "4631", name: "Bán buôn lương thực" },
  { code: "4632", name: "Bán buôn thực phẩm" },
  { code: "4633", name: "Bán buôn đồ uống" },
  { code: "4634", name: "Bán buôn sản phẩm thuốc lá, thuốc lào" },
  { code: "4641", name: "Bán buôn vải, hàng may sẵn, giày dép" },
  { code: "4649", name: "Bán buôn đồ dùng khác cho gia đình" },
  { code: "4651", name: "Bán buôn máy vi tính, thiết bị ngoại vi và phần mềm" },
  { code: "4652", name: "Bán buôn thiết bị và linh kiện điện tử, viễn thông" },
  { code: "4653", name: "Bán buôn máy móc, thiết bị và phụ tùng máy nông nghiệp" },
  { code: "4659", name: "Bán buôn máy móc, thiết bị và phụ tùng máy khác" },
  { code: "4661", name: "Bán buôn nhiên liệu rắn, lỏng, khí và các sản phẩm liên quan" },
  { code: "4662", name: "Bán buôn kim loại và quặng kim loại" },
  { code: "4663", name: "Bán buôn vật liệu, thiết bị lắp đặt khác trong xây dựng" },
  { code: "4669", name: "Bán buôn chuyên doanh khác chưa được phân vào đâu" },
  { code: "4690", name: "Bán buôn tổng hợp" },
  { code: "4711", name: "Bán lẻ trong các cửa hàng kinh doanh tổng hợp (siêu thị, tạp hóa)" },
  { code: "4719", name: "Bán lẻ khác trong các cửa hàng kinh doanh tổng hợp" },
  { code: "4721", name: "Bán lẻ lương thực trong các cửa hàng chuyên doanh" },
  { code: "4722", name: "Bán lẻ thực phẩm trong các cửa hàng chuyên doanh" },
  { code: "4730", name: "Bán lẻ nhiên liệu động cơ trong các cửa hàng chuyên doanh" },
  { code: "4741", name: "Bán lẻ máy vi tính, thiết bị ngoại vi, phần mềm và viễn thông" },
  { code: "4752", name: "Bán lẻ thiết bị ngũ kim, sơn, kính trong các cửa hàng chuyên doanh" },
  { code: "4753", name: "Bán lẻ thảm, đệm, chăn, màn, rèm cửa, vật liệu phủ tường và sàn" },
  { code: "4771", name: "Bán lẻ hàng may mặc, giày dép, hàng da trong cửa hàng chuyên doanh" },
  { code: "4772", name: "Bán lẻ thuốc, dụng cụ y tế, mỹ phẩm trong cửa hàng chuyên doanh" },
  { code: "4773", name: "Bán lẻ hàng hóa mới khác trong các cửa hàng chuyên doanh" },
  { code: "4791", name: "Bán lẻ theo yêu cầu thư tín hoặc internet (thương mại điện tử)" },
  { code: "4799", name: "Bán lẻ hình thức khác không qua cửa hàng" },
  { code: "4911", name: "Vận tải hành khách đường sắt" },
  { code: "4912", name: "Vận tải hàng hóa đường sắt" },
  { code: "4921", name: "Vận tải hành khách đường bộ trong nội thành, ngoại thành (xe buýt)" },
  { code: "4922", name: "Vận tải hành khách đường bộ khác (taxi, xe khách)" },
  { code: "4933", name: "Vận tải hàng hóa bằng đường bộ" },
  { code: "5011", name: "Vận tải hành khách đường biển" },
  { code: "5012", name: "Vận tải hàng hóa đường biển" },
  { code: "5110", name: "Vận tải hành khách đường hàng không" },
  { code: "5120", name: "Vận tải hàng hóa đường hàng không" },
  { code: "5210", name: "Kho bãi và lưu giữ hàng hóa" },
  { code: "5224", name: "Bốc xếp hàng hóa" },
  { code: "5229", name: "Hoạt động dịch vụ hỗ trợ khác liên quan đến vận tải (logistics)" },
  { code: "5510", name: "Dịch vụ lưu trú ngắn ngày (khách sạn, nhà nghỉ)" },
  { code: "5590", name: "Cơ sở lưu trú khác (ký túc xá, nhà trọ)" },
  { code: "5610", name: "Dịch vụ ăn uống phục vụ tại chỗ (nhà hàng, quán ăn)" },
  { code: "5621", name: "Cung cấp dịch vụ ăn uống theo hợp đồng (tiệc cưới, sự kiện)" },
  { code: "5629", name: "Dịch vụ ăn uống khác (căng tin, quán ăn nhanh)" },
  { code: "5630", name: "Dịch vụ phục vụ đồ uống (quán cà phê, giải khát, bar)" },
  { code: "5811", name: "Xuất bản sách" },
  { code: "5812", name: "Xuất bản danh bạ và các loại tương tự" },
  { code: "5813", name: "Xuất bản báo, tạp chí và các ấn phẩm định kỳ" },
  { code: "5820", name: "Xuất bản phần mềm" },
  { code: "5911", name: "Hoạt động sản xuất phim điện ảnh, phim video và chương trình truyền hình" },
  { code: "5912", name: "Hoạt động hậu kỳ" },
  { code: "6110", name: "Viễn thông có dây" },
  { code: "6120", name: "Viễn thông không dây" },
  { code: "6201", name: "Lập trình máy tính" },
  { code: "6202", name: "Tư vấn máy tính và quản trị hệ thống máy tính" },
  { code: "6209", name: "Hoạt động dịch vụ công nghệ thông tin và dịch vụ khác liên quan đến máy tính" },
  { code: "6311", name: "Xử lý dữ liệu, cho thuê hosting và các hoạt động liên quan" },
  { code: "6312", name: "Cổng thông tin" },
  { code: "6411", name: "Hoạt động ngân hàng trung ương" },
  { code: "6419", name: "Hoạt động trung gian tiền tệ khác (ngân hàng thương mại)" },
  { code: "6420", name: "Hoạt động công ty nắm giữ tài sản (Holding)" },
  { code: "6430", name: "Hoạt động quỹ tín thác, các quỹ và các tổ chức tài chính tương tự" },
  { code: "6491", name: "Hoạt động cho thuê tài chính" },
  { code: "6492", name: "Hoạt động cấp tín dụng khác (tiệm cầm đồ, cho vay tiêu dùng)" },
  { code: "6511", name: "Bảo hiểm nhân thọ" },
  { code: "6512", name: "Bảo hiểm phi nhân thọ" },
  { code: "6612", name: "Môi giới hợp đồng hàng hóa và chứng khoán" },
  { code: "6619", name: "Hoạt động hỗ trợ dịch vụ tài chính chưa phân vào đâu" },
  { code: "6810", name: "Kinh doanh bất động sản, quyền sử dụng đất thuộc chủ sở hữu, chủ sử dụng hoặc đi thuê" },
  { code: "6820", name: "Tư vấn, môi giới, đấu giá bất động sản, đấu giá quyền sử dụng đất" },
  { code: "6910", name: "Hoạt động pháp luật (luật sư, công chứng)" },
  { code: "6920", name: "Hoạt động kế toán, kiểm toán và tư vấn về thuế" },
  { code: "7010", name: "Hoạt động của văn phòng trụ sở chính" },
  { code: "7020", name: "Hoạt động tư vấn quản lý" },
  { code: "7110", name: "Hoạt động kiến trúc và tư vấn kỹ thuật có liên quan" },
  { code: "7120", name: "Kiểm tra và phân tích kỹ thuật" },
  { code: "7211", name: "Nghiên cứu khoa học và phát triển công nghệ trong lĩnh vực công nghệ sinh học" },
  { code: "7310", name: "Quảng cáo" },
  { code: "7320", name: "Nghiên cứu thị trường và thăm dò dư luận" },
  { code: "7410", name: "Hoạt động thiết kế chuyên dụng (thiết kế thời trang, nội thất)" },
  { code: "7420", name: "Hoạt động nhiếp ảnh" },
  { code: "7490", name: "Hoạt động chuyên môn, khoa học và công nghệ khác chưa phân vào đâu" },
  { code: "7710", name: "Cho thuê xe có động cơ" },
  { code: "7730", name: "Cho thuê máy móc, thiết bị và đồ dùng hữu hình khác không kèm người điều khiển" },
  { code: "7810", name: "Hoạt động của các đại lý môi giới lao động, việc làm" },
  { code: "7820", name: "Cung ứng và quản lý lao động tạm thời" },
  { code: "7911", name: "Đại lý du lịch" },
  { code: "7912", name: "Điều hành tua du lịch" },
  { code: "8010", name: "Dịch vụ bảo vệ tư nhân" },
  { code: "8121", name: "Vệ sinh chung nhà cửa" },
  { code: "8211", name: "Dịch vụ hành chính văn phòng tổng hợp" },
  { code: "8230", name: "Tổ chức giới thiệu và xúc tiến thương mại (sự kiện, hội chợ)" },
  { code: "8511", name: "Giáo dục tiểu học" },
  { code: "8512", name: "Giáo dục trung học cơ sở và trung học phổ thông" },
  { code: "8521", name: "Đào tạo sơ cấp" },
  { code: "8522", name: "Đào tạo trung cấp, cao đẳng" },
  { code: "8531", name: "Đào tạo đại học" },
  { code: "8532", name: "Đào tạo sau đại học" },
  { code: "8551", name: "Đào tạo thể thao và giải trí" },
  { code: "8552", name: "Đào tạo văn hoá nghệ thuật" },
  { code: "8559", name: "Giáo dục khác chưa phân vào đâu (trung tâm ngoại ngữ, tin học, bồi dưỡng văn hóa)" },
  { code: "8610", name: "Hoạt động của các bệnh viện, phòng khám" },
  { code: "8620", name: "Hoạt động nha khoa" },
  { code: "8690", name: "Hoạt động y tế khác chưa phân vào đâu" },
  { code: "8710", name: "Hoạt động chăm sóc sức khỏe điều dưỡng tập trung" },
  { code: "8810", name: "Hoạt động trợ giúp xã hội không tập trung đối với người già và người khuyết tật" },
  { code: "9000", name: "Hoạt động sáng tạo, nghệ thuật và giải trí" },
  { code: "9102", name: "Hoạt động của bảo tàng, nhà bảo tồn" },
  { code: "9200", name: "Hoạt động vui chơi giải trí và xổ số, cá cược" },
  { code: "9311", name: "Hoạt động của các cơ sở thể thao" },
  { code: "9312", name: "Hoạt động của các câu lạc bộ thể thao" },
  { code: "9329", name: "Hoạt động vui chơi giải trí khác chưa phân vào đâu" },
  { code: "9511", name: "Sửa chữa máy vi tính và thiết bị ngoại vi" },
  { code: "9512", name: "Sửa chữa thiết bị truyền thông (điện thoại)" },
  { code: "9521", name: "Sửa chữa sản phẩm điện tử dân dụng trong gia đình" },
  { code: "9522", name: "Sửa chữa thiết bị gia dụng và đồ dùng gia đình" },
  { code: "9601", name: "Giặt là, làm sạch các sản phẩm dệt và lông thú" },
  { code: "9602", name: "Dịch vụ cắt tóc, làm đầu, gội đầu" },
  { code: "9603", name: "Dịch vụ phục vụ cá nhân khác chưa phân vào đâu (spa, xông hơi)" },
];
